api_platform:
  show_webby: false
  mapping:
    paths: [ "%kernel.project_dir%/src/Entity" ]
  formats:
    jsonld: [ "application/ld+json" ]
    json: [ "application/json" ]
    html: [ "text/html" ]
    multipart: [ "multipart/form-data" ]
    pdf: ["application/pdf"]
  patch_formats:
    json: [ "application/merge-patch+json" ]
  swagger:
    versions: [ 3 ]
