vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    customer_picture:
      uri_prefix: /images/customers
      upload_destination: "%kernel.project_dir%/public/images/customers"
      namer: Vich\UploaderBundle\Naming\OrignameNamer