version: "3.8"

services: 
  # Nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    restart: always
    ports:
      - "8080:80"
    volumes: 
      - .:/var/www/
      - ./website.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php8-service
      - mysql8-service

  # PHP
  php8-service:
    build: .
    container_name: php8-container
    restart: always
    ports:
      - "9000:9000"
    volumes: 
      - .:/var/www/
    depends_on:
      - mysql8-service

  # MySQL
  mysql8-service:
    image: mysql:8
    container_name: mysql8-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - "4306:3306"
    volumes: 
      - db_data:/var/lib/mysql
      - ./var:/var/www/var
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    ports:
      - "8081:80"
    depends_on: 
      - mysql8-service
    environment:
      - PMA_ARBITRARY=1

  # Maildev
  maildev-service:
    image: maildev/maildev
    container_name: maildev-container
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    restart: always
    ports:
      - "8082:80"
      
volumes: 
  db_data: {}