#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
  path: /api/authentication_token

gesdinet_jwt_refresh_token:
  path: /api/authentication_token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

logout:
  path: /api/authentication_token/revoke
  controller: App\Controller\Auth\Logout::logout
