name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Docker Compose stack
        run: |-
          docker-compose pull --ignore-pull-failures
          docker-compose up -d --build
          docker exec php8-container composer install -o -n
          docker-compose run node-service yarn install
      - name: PHP Tests
        run: |-
          docker exec php8-container openssl genpkey -out config/jwt/private.pem -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096 -pass pass:test
          docker exec php8-container openssl pkey -in config/jwt/private.pem -out config/jwt/public.pem -pubout -passin pass:test
          docker exec php8-container php bin/phpunit
      - name: ESlint
        run: docker-compose run node-service yarn lint
      - name: JavaScript Tests
        run: docker-compose run node-service yarn test