name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Docker Compose stack
        run: |-
          docker-compose pull --ignore-pull-failures
          docker-compose build --pull
          docker-compose run php8-service composer install -o -n
          docker-compose up -d
      - name: Generate JWT keys
        run: |-
          docker-compose exec -T php8-service openssl genpkey -out config/jwt/private.pem -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096 -pass pass:test
          docker-compose exec -T php8-service openssl pkey -in config/jwt/private.pem -out config/jwt/public.pem -pubout -passin pass:test
      - name: Tests
        run: docker-compose exec -T php8-service php bin/phpunit